GET http://127.0.0.1:8080/patientenAll
###
POST http://127.0.0.1:8080/api/benutzerverwaltung 
Content-Type: application/json

{
    "userID": "thorgebreitzmann",
    "password": "securepassword",
    "rolle": 0
}